### ISSUE TITLE
Information on repo is incorrect

### ISSUE THREAD

**Issue by MagicLegend** [nyuszika7h/reprovisionfix#1]
Hey,

The information on the repo is from your other tweak otaenabler: https://repo.cadoth.net/depictions/net.cadoth.reprovisionfix

Looks kinda scary when you're just trying to get Reprovision fixed :) Would be nice if it can be updated!

**Comment by ghost** [comment]
Oops, fixed. (You should probably be using ReProvision Reborn now instead though, it fixes more issues especially if you're on 13.5+ or 14.0+.)
